package com.spendesk.grapes.compose.theme

import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

/**
 * @author : danyboucanova
 * @since : 18/05/2022, Wed
 **/
@Suppress("LongParameterList", "LongMethod")
fun lightColorsPalette(
    primaryDark: Color = purpleDark,
    primaryNormal: Color = purpleNormal,
    primaryLight: Color = purpleLight,
    primaryLighter: Color = purpleLighter,
    primaryLightest: Color = purpleLightest,

    white: Color = grayWhite,
    surface: Color = white,
    complementary: Color = purpleDarker,
    background: Color = graySuperLightest,

    neutralDarker: Color = grayDarker,
    neutralLightest: Color = grayLightest,
    neutralDark: Color = grayDark,
    neutralNormal: Color = grayNormal,
    neutralLight: Color = grayLight,
    neutralLighter: Color = grayLighter,

    infoNormal: Color = blueNormal,
    infoLighter: Color = blueLighter,
    infoLightest: Color = blueLightest,

    successNormal: Color = greenNormal,
    successLighter: Color = greenLight,
    successLightest: Color = greenLighter,

    warningDark: Color = orangeDark,
    warningNormal: Color = orangeNormal,
    warningLight: Color = orangeLight,
    warningLighter: Color = orangeLighter,
    warningLightest: Color = orangeLightest,

    alertDark: Color = redDark,
    alertNormal: Color = redNormal,
    alertLight: Color = redLight,
    alertLighter: Color = redLighter,
    alertLightest: Color = redLightest,
    backgroundPrimary: Color = white,
    backgroundSecondary: Color = carbon3,
    backgroundTertiary: Color = carbon10,
    backgroundHover: Color = carbon3,
    backgroundPressed: Color = carbon10,
    backgroundSelected: Color = purple10,
    backgroundDisabled: Color = carbon5,
    backgroundReadOnly: Color = carbon3,
    backgroundPrimaryBrandDefault: Color = purple70,
    backgroundPrimaryBrandHover: Color = purple80,
    backgroundPrimaryBrandPressed: Color = purple90,
    backgroundPrimaryInfoDefault: Color = purple70,
    backgroundPrimaryInfoHover: Color = purple80,
    backgroundPrimaryInfoPressed: Color = purple90,
    backgroundPrimarySuccessDefault: Color = emerald70,
    backgroundPrimarySuccessHover: Color = emerald80,
    backgroundPrimarySuccessPressed: Color = emerald90,
    backgroundPrimaryWarningDefault: Color = apricot70,
    backgroundPrimaryWarningHover: Color = apricot80,
    backgroundPrimaryWarningPressed: Color = apricot90,
    backgroundPrimaryAlertDefault: Color = raspberry70,
    backgroundPrimaryAlertHover: Color = raspberry80,
    backgroundPrimaryAlertPressed: Color = raspberry90,
    backgroundSecondaryBrandDefault: Color = purple10,
    backgroundSecondaryBrandHover: Color = purple10,
    backgroundSecondaryBrandPressed: Color = purple20,
    backgroundSecondaryInfoDefault: Color = blue10,
    backgroundSecondaryInfoHover: Color = blue10,
    backgroundSecondaryInfoPressed: Color = blue20,
    backgroundSecondarySuccessDefault: Color = emerald10,
    backgroundSecondarySuccessHover: Color = emerald10,
    backgroundSecondarySuccessPressed: Color = emerald20,
    backgroundSecondaryWarningDefault: Color = apricot10,
    backgroundSecondaryWarningHover: Color = apricot10,
    backgroundSecondaryWarningPressed: Color = apricot20,
    backgroundSecondaryAlertDefault: Color = raspberry10,
    backgroundSecondaryAlertHover: Color = raspberry10,
    backgroundSecondaryAlertPressed: Color = raspberry20,
    contentPrimary: Color = carbon100,
    contentSecondary: Color = carbon70,
    contentTertiary: Color = carbon60,
    contentComplementary: Color = white,
    contentSelected: Color = purple70,
    contentDisable: Color = carbon20,
    contentBrandDefault: Color = purple70,
    contentBrandHover: Color = purple90,
    contentBrandPressed: Color = purple90,
    contentInfoDefault: Color = blue70,
    contentSuccessDefault: Color = emerald70,
    contentWarningDefault: Color = apricot70,
    contentAlertDefault: Color = raspberry70,

    borderDefault: Color = carbon10,
    borderHover: Color = purple90,
    borderSelected: Color = purple70,
    borderInfo: Color = blue70,
    borderSuccess: Color = emerald70,
    borderWarning: Color = apricot70,
    borderAlert: Color = raspberry70,
): GrapesColors = GrapesColors(
    mainWhite = white,
    google = google,
    primaryDark = primaryDark,
    primaryNormal = primaryNormal,
    primaryLight = primaryLight,
    primaryLighter = primaryLighter,
    primaryLightest = primaryLightest,
    neutralDarker = neutralDarker,
    neutralDark = neutralDark,
    neutralNormal = neutralNormal,
    neutralLight = neutralLight,
    neutralLighter = neutralLighter,
    neutralLightest = neutralLightest,
    infoNormal = infoNormal,
    infoLighter = infoLighter,
    infoLightest = infoLightest,
    successNormal = successNormal,
    successLighter = successLighter,
    successLightest = successLightest,
    warningDark = warningDark,
    warningNormal = warningNormal,
    warningLight = warningLight,
    warningLighter = warningLighter,
    warningLightest = warningLightest,
    alertDark = alertDark,
    alertNormal = alertNormal,
    alertLight = alertLight,
    alertLighter = alertLighter,
    alertLightest = alertLightest,
    structureSurface = surface,
    structureComplementary = complementary,
    structureBackground = background,
    isLight = true,
    backgroundPrimary = backgroundPrimary,
    backgroundSecondary = backgroundSecondary,
    backgroundTertiary = backgroundTertiary,
    backgroundHover = backgroundHover,
    backgroundPressed = backgroundPressed,
    backgroundSelected = backgroundSelected,
    backgroundDisabled = backgroundDisabled,
    backgroundReadOnly = backgroundReadOnly,
    backgroundPrimaryBrandDefault = backgroundPrimaryBrandDefault,
    backgroundPrimaryBrandHover = backgroundPrimaryBrandHover,
    backgroundPrimaryBrandPressed = backgroundPrimaryBrandPressed,
    backgroundPrimaryInfoDefault = backgroundPrimaryInfoDefault,
    backgroundPrimaryInfoHover = backgroundPrimaryInfoHover,
    backgroundPrimaryInfoPressed = backgroundPrimaryInfoPressed,
    backgroundPrimarySuccessDefault = backgroundPrimarySuccessDefault,
    backgroundPrimarySuccessHover = backgroundPrimarySuccessHover,
    backgroundPrimarySuccessPressed = backgroundPrimarySuccessPressed,
    backgroundPrimaryWarningDefault = backgroundPrimaryWarningDefault,
    backgroundPrimaryWarningHover = backgroundPrimaryWarningHover,
    backgroundPrimaryWarningPressed = backgroundPrimaryWarningPressed,
    backgroundPrimaryAlertDefault = backgroundPrimaryAlertDefault,
    backgroundPrimaryAlertHover = backgroundPrimaryAlertHover,
    backgroundPrimaryAlertPressed = backgroundPrimaryAlertPressed,
    backgroundSecondaryBrandDefault = backgroundSecondaryBrandDefault,
    backgroundSecondaryBrandHover = backgroundSecondaryBrandHover,
    backgroundSecondaryBrandPressed = backgroundSecondaryBrandPressed,
    backgroundSecondaryInfoDefault = backgroundSecondaryInfoDefault,
    backgroundSecondaryInfoHover = backgroundSecondaryInfoHover,
    backgroundSecondaryInfoPressed = backgroundSecondaryInfoPressed,
    backgroundSecondarySuccessDefault = backgroundSecondarySuccessDefault,
    backgroundSecondarySuccessHover = backgroundSecondarySuccessHover,
    backgroundSecondarySuccessPressed = backgroundSecondarySuccessPressed,
    backgroundSecondaryWarningDefault = backgroundSecondaryWarningDefault,
    backgroundSecondaryWarningHover = backgroundSecondaryWarningHover,
    backgroundSecondaryWarningPressed = backgroundSecondaryWarningPressed,
    backgroundSecondaryAlertDefault = backgroundSecondaryAlertDefault,
    backgroundSecondaryAlertHover = backgroundSecondaryAlertHover,
    backgroundSecondaryAlertPressed = backgroundSecondaryAlertPressed,
    contentPrimary = contentPrimary,
    contentSecondary = contentSecondary,
    contentTertiary = contentTertiary,
    contentComplementary = contentComplementary,
    contentSelected = contentSelected,
    contentDisable = contentDisable,
    contentBrandDefault = contentBrandDefault,
    contentBrandHover = contentBrandHover,
    contentBrandPressed = contentBrandPressed,
    contentInfoDefault = contentInfoDefault,
    contentSuccessDefault = contentSuccessDefault,
    contentWarningDefault = contentWarningDefault,
    contentAlertDefault = contentAlertDefault,
    borderDefault = borderDefault,
    borderHover = borderHover,
    borderSelected = borderSelected,
    borderInfo = borderInfo,
    borderSuccess = borderSuccess,
    borderWarning = borderWarning,
    borderAlert = borderAlert,
)

internal val LocalGrapesColors = staticCompositionLocalOf { lightColorsPalette() }
