complexity:
  LongMethod:
    ignoreAnnotated: [ 'Composable' ]
  LongParameterList:
    ignoreDataClasses: true
    ignoreDefaultParameters: true
    ignoreAnnotated: [ 'Composable' ]
formatting:
  ArgumentListWrapping:
    maxLineLength: 200
  ContextReceiverMapping:
    maxLineLength: 200
  FunctionReturnTypeSpacing:
    maxLineLength: 200
  FunctionSignature:
    maxLineLength: 200
  ImportOrdering:
    active: false
  MaximumLineLength:
    maxLineLength: 200
  ParameterListWrapping:
    maxLineLength: 200
  ParameterWrapping:
    maxLineLength: 200
  PropertyWrapping:
    maxLineLength: 200
  Wrapping:
    maxLineLength: 200
naming:
  FunctionNaming:
    ignoreAnnotated: [ 'Composable' ]
  TopLevelPropertyNaming:
    constantPattern: '[A-Z][_A-Za-z0-9]*'
style:
  MagicNumber:
    ignorePropertyDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
  MaxLineLength:
    active: true
    maxLineLength: 200
    excludeCommentStatements: false
  UnusedPrivateMember:
    ignoreAnnotated: [ 'Preview' ]
